name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          geetasree0103/todo-app:v1.0.${{ github.run_number }}
          geetasree0103/todo-app:latest
    
    - name: Set up kubectl
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG }}
    
    - name: Deploy to Kubernetes
      run: |
        sed -i "s|IMAGE_TAG|v1.0.${{ github.run_number }}|g" k8s/deployment.yaml
        kubectl apply -f k8s/
        kubectl set image deployment/todo-app todo-app=geetasree0103/todo-app:v1.0.${{ github.run_number }} --record
        kubectl rollout status deployment/todo-app --timeout=300s
